// Chapter-detection harness. Runs detectChaptersFromText against every
// fixture in test/fixtures/ (synthetic) and test/corpus/ (real downloads),
// scoring detected chapters against expected ground truth.
//
// Usage:
//   bun test/harness.ts                 # synthetic fixtures only
//   bun test/harness.ts --corpus        # real PDFs only
//   bun test/harness.ts --all           # both
//   bun test/harness.ts --only <name>   # one fixture by name
//   bun test/harness.ts --category <c>  # filter by category
//   bun test/harness.ts --verbose       # full per-fixture diff
//
// Expected ground truth comes from `<name>.expected.json` (generated by the
// corpus puller or hand-written for real fixtures).

import { readFileSync, readdirSync, existsSync } from "fs";
import { resolve } from "path";
import { pathToFileURL } from "url";

import * as pdfjs from "pdfjs-dist/legacy/build/pdf.mjs";
pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(
  resolve(import.meta.dir, "../node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs"),
).href;

const { detectChaptersFromText } = await import("../src/lib/pdf");

const FIXTURES_DIR = resolve(import.meta.dir, "fixtures");
const CORPUS_DIR = resolve(import.meta.dir, "corpus");

interface Expected {
  description: string;
  category?: string;
  source?: "embedded-outline" | "no-outline" | "hand";
  chapters: { title: string; page: number; level?: number }[];
}

interface Detected { title: string; page: number; level: number }

interface Result {
  name: string;
  category: string;
  description: string;
  source: string;
  expected: Expected["chapters"];
  detected: Detected[];
  pagesMatched: number;
  titlesMatched: number;
  extras: number;
  missing: number;
  pass: boolean;
  skipped: boolean;
  reason?: string;
}

function normalize(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function titlesShareToken(a: string, b: string): boolean {
  const na = normalize(a);
  const nb = normalize(b);
  if (na === nb) return true;
  // Squashed form: drop ALL whitespace. Catches drop-cap spacing artifacts
  // ("d ebert axxl" ≈ "deberta xxl" → both become "debertaxxl").
  const sa = na.replace(/\s+/g, "");
  const sb = nb.replace(/\s+/g, "");
  if (sa && sb) {
    if (sa === sb) return true;
    if (sa.length >= 5 && sb.length >= 5) {
      if (sa.includes(sb) || sb.includes(sa)) return true;
    }
  }
  // Short-title match (common for novels where chapters are just "I", "II"):
  // if either normalized title is a complete-token prefix/substring of the
  // other (word-boundary), count as a match.
  if (na && nb) {
    const inB = new RegExp(`\\b${na.replace(/[^a-z0-9 ]/g, "")}\\b`).test(nb);
    const inA = new RegExp(`\\b${nb.replace(/[^a-z0-9 ]/g, "")}\\b`).test(na);
    if (inB || inA) return true;
  }
  const A = na.split(/\s+/).filter((t) => t.length >= 3);
  const B = new Set(nb.split(/\s+/).filter((t) => t.length >= 3));
  if (A.length === 0 || B.size === 0) return na === nb;
  for (const t of A) if (B.has(t)) return true;
  return false;
}

interface Scored { pagesMatched: number; titlesMatched: number; claimed: Set<number>; recall: number; precision: number; titleRate: number; f1: number }

function scoreLevel(detected: Detected[], expected: { title: string; page: number }[]): Scored {
  const claimed = new Set<number>();
  let pagesMatched = 0;
  let titlesMatched = 0;
  for (const e of expected) {
    let bestIdx = -1;
    let bestDiff = Infinity;
    for (let i = 0; i < detected.length; i++) {
      if (claimed.has(i)) continue;
      const d = Math.abs(detected[i].page - e.page);
      if (d < bestDiff) { bestDiff = d; bestIdx = i; }
    }
    if (bestIdx >= 0 && bestDiff <= 3) {
      claimed.add(bestIdx);
      pagesMatched++;
      if (titlesShareToken(e.title, detected[bestIdx].title)) titlesMatched++;
    }
  }
  const recall = expected.length > 0 ? pagesMatched / expected.length : 0;
  const precision = detected.length > 0 ? claimed.size / detected.length : 0;
  const titleRate = pagesMatched > 0 ? titlesMatched / pagesMatched : 0;
  const f1 = recall + precision > 0 ? (2 * recall * precision) / (recall + precision) : 0;
  return { pagesMatched, titlesMatched, claimed, recall, precision, titleRate, f1 };
}

async function runOne(name: string, pdfPath: string, expectedPath: string): Promise<Result> {
  const raw: Expected = JSON.parse(readFileSync(expectedPath, "utf8"));
  const category = raw.category ?? "unknown";
  const source = raw.source ?? "hand";

  if (raw.chapters.length < 2) {
    return {
      name, category, description: raw.description, source,
      expected: [], detected: [],
      pagesMatched: 0, titlesMatched: 0, extras: 0, missing: 0,
      pass: false, skipped: true, reason: "no ground truth",
    };
  }

  const bytes = readFileSync(pdfPath);
  const doc = await pdfjs.getDocument({ data: new Uint8Array(bytes), isEvalSupported: false }).promise;

  let detected: Detected[] = [];
  try {
    const items = await detectChaptersFromText(doc);
    detected = items
      .filter((c) => c.page != null)
      .map((c) => ({ title: c.title, page: c.page as number, level: c.level }));
  } catch (e: any) {
    await doc.destroy();
    return {
      name, category, description: raw.description, source,
      expected: raw.chapters, detected: [],
      pagesMatched: 0, titlesMatched: 0, extras: 0, missing: raw.chapters.length,
      pass: false, skipped: false,
      reason: `detection error: ${e?.message ?? e}`,
    };
  }
  await doc.destroy();

  // The embedded outline may have multiple levels (parts vs chapters vs
  // sub-sections). Our detector produces a flat chapter list, so grade
  // against whichever outline level best aligns with what we produced — the
  // level that maximizes F1. This is fair: if the detector recovers
  // chapter-level granularity, it shouldn't be penalized for not also
  // recovering sub-section starts.
  const byLevel = new Map<number, { title: string; page: number }[]>();
  for (const c of raw.chapters) {
    const l = c.level ?? 0;
    const arr = byLevel.get(l) ?? [];
    arr.push(c);
    byLevel.set(l, arr);
  }

  let bestLevel = 0;
  let best: Scored = { pagesMatched: 0, titlesMatched: 0, claimed: new Set(), recall: 0, precision: 0, titleRate: 0, f1: -1 };
  let bestExpected = raw.chapters;
  for (const [l, list] of byLevel) {
    if (list.length < 2) continue;
    const s = scoreLevel(detected, list);
    if (s.f1 > best.f1) {
      best = s;
      bestLevel = l;
      bestExpected = list;
    }
  }
  // If no level had enough entries, fall back to flat grading.
  if (best.f1 < 0) {
    best = scoreLevel(detected, raw.chapters);
    bestExpected = raw.chapters;
  }

  // Precision: penalize only detections that don't match ANY expected entry
  // at ANY level. A detected sub-section that is a real heading in the doc
  // but not in the best-level slice shouldn't count as an extra.
  const allExpected = raw.chapters;
  let matchedAgainstAny = 0;
  for (const d of detected) {
    for (const e of allExpected) {
      if (Math.abs(d.page - e.page) <= 3) { matchedAgainstAny++; break; }
    }
  }
  const adjPrecision = detected.length > 0 ? matchedAgainstAny / detected.length : 0;

  const extras = detected.length - matchedAgainstAny;
  const missing = bestExpected.length - best.pagesMatched;

  const pass = best.recall >= 0.7 && adjPrecision >= 0.5 && best.titleRate >= 0.5;

  return {
    name, category, description: raw.description + ` (graded vs level ${bestLevel}: ${bestExpected.length})`, source,
    expected: bestExpected, detected,
    pagesMatched: best.pagesMatched, titlesMatched: best.titlesMatched, extras, missing,
    pass, skipped: false,
  };
}

function enumerate(dir: string, maxMb = 60): { name: string; pdf: string; expected: string }[] {
  if (!existsSync(dir)) return [];
  const pdfs = readdirSync(dir).filter((f) => f.endsWith(".pdf"));
  const out: { name: string; pdf: string; expected: string }[] = [];
  for (const f of pdfs) {
    const name = f.replace(/\.pdf$/, "");
    const pdfPath = resolve(dir, f);
    const { size } = readFileStat(pdfPath);
    if (size > maxMb * 1024 * 1024) continue;  // skip huge PDFs
    const expected = resolve(dir, `${name}.expected.json`);
    if (existsSync(expected)) out.push({ name, pdf: pdfPath, expected });
  }
  return out;
}

function readFileStat(p: string): { size: number } {
  // Tiny helper so we don't import fs.statSync at the top.
  const { statSync } = require("fs");
  return { size: statSync(p).size };
}

function formatResult(r: Result, verbose: boolean): string {
  if (r.skipped) return `\x1b[90mSKIP\x1b[0m  ${r.name.padEnd(40)} ${r.reason}`;
  const color = r.pass ? "\x1b[32m" : "\x1b[31m";
  const tag = r.pass ? "PASS" : "FAIL";
  const summary = `${r.pagesMatched}/${r.expected.length} pages, ${r.titlesMatched}/${r.pagesMatched || 0} titles, +${r.extras} extras`;
  let line = `${color}${tag}\x1b[0m  ${r.name.padEnd(40)} [${r.category}]  ${summary}`;
  if (r.reason) line += `  — ${r.reason}`;
  if (!verbose || r.pass) return line;

  // Verbose: show diff
  const out: string[] = [line];
  const shown = Math.min(6, r.expected.length);
  for (let i = 0; i < shown; i++) {
    const e = r.expected[i];
    const d = r.detected.find((x) => Math.abs(x.page - e.page) <= 3);
    if (d) out.push(`      ✓ p${e.page} "${e.title.slice(0, 60)}" → p${d.page} "${d.title.slice(0, 60)}"`);
    else out.push(`      ✗ p${e.page} "${e.title.slice(0, 60)}" → (none)`);
  }
  return out.join("\n");
}

async function main() {
  const args = process.argv.slice(2);
  const wantCorpus = args.includes("--corpus") || args.includes("--all");
  const wantFixtures = args.includes("--all") || !wantCorpus;
  const verbose = args.includes("--verbose");
  const onlyIdx = args.indexOf("--only");
  const only = onlyIdx >= 0 ? args[onlyIdx + 1] : undefined;
  const catIdx = args.indexOf("--category");
  const categoryFilter = catIdx >= 0 ? args[catIdx + 1] : undefined;

  let entries: { name: string; pdf: string; expected: string }[] = [];
  if (wantFixtures) entries = entries.concat(enumerate(FIXTURES_DIR));
  if (wantCorpus) entries = entries.concat(enumerate(CORPUS_DIR));

  if (only) entries = entries.filter((e) => e.name === only);
  entries.sort((a, b) => a.name.localeCompare(b.name));

  if (entries.length === 0) {
    console.error("No fixtures to run.");
    process.exit(1);
  }

  console.log(`Harness · ${entries.length} target(s)${only ? ` (only=${only})` : ""}${categoryFilter ? ` (category=${categoryFilter})` : ""}`);

  const results: Result[] = [];
  let done = 0;
  for (const e of entries) {
    done++;
    try {
      const r = await runOne(e.name, e.pdf, e.expected);
      if (categoryFilter && r.category !== categoryFilter) continue;
      results.push(r);
      console.log(`[${done}/${entries.length}] ` + formatResult(r, verbose));
    } catch (err: any) {
      console.log(`[${done}/${entries.length}] \x1b[31mERROR\x1b[0m ${e.name} — ${err?.message ?? err}`);
    }
  }

  // Category roll-up.
  const byCat = new Map<string, { passed: number; failed: number; skipped: number }>();
  for (const r of results) {
    const b = byCat.get(r.category) ?? { passed: 0, failed: 0, skipped: 0 };
    if (r.skipped) b.skipped++;
    else if (r.pass) b.passed++;
    else b.failed++;
    byCat.set(r.category, b);
  }
  console.log("\n── Summary by category ──");
  for (const [c, b] of [...byCat.entries()].sort()) {
    const total = b.passed + b.failed + b.skipped;
    console.log(`  ${c.padEnd(12)} ${b.passed}/${b.passed + b.failed} passed  (${b.skipped} skipped, ${total} total)`);
  }

  const passed = results.filter((r) => r.pass).length;
  const failed = results.filter((r) => !r.pass && !r.skipped).length;
  const skipped = results.filter((r) => r.skipped).length;
  console.log(`\nTotal: ${passed} passed / ${failed} failed / ${skipped} skipped`);
  process.exit(failed === 0 ? 0 : 1);
}

await main();
